@extends('layouts.main')

@section('content')
@foreach ($blogs as $blog )
<div class="col-lg-8 mx-auto">
    <h1 class="post-title">{{ $blog->title }}</h1>
   <small class="my-4">Created by<a href=""> Rengga Maulana</a>. 3 days ago</small> 
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime, perferendis hic eos labore sit modi quia fuga placeat exercitationem natus inventore in. Sint qui ducimus sapiente quasi quo quaerat, nobis consequatur omnis distinctio necessitatibus perferendis adipisci error architecto reiciendis neque optio, exercitationem maiores, atque nulla doloribus eos expedita unde. Quaerat rem eum molestiae iste minus iure nobis recusandae impedit corporis est perspiciatis eius quas, sed fuga architecto molestias quasi nostrum vero, explicabo aut iusto. Voluptates nam laboriosam at aperiam beatae vel, veritatis, dignissimos ab minus ipsum praesentium voluptatum! Corporis quo inventore incidunt fugiat officia, suscipit veritatis dolorem exercitationem soluta quam consectetur minima! Quos qui amet adipisci veniam velit dignissimos iusto, non, error vel quae accusantium sit incidunt expedita molestias modi quidem atque obcaecati maxime soluta? Animi quia distinctio qui deserunt, unde veritatis? Voluptatibus ipsa id est laboriosam, enim, fuga totam, animi voluptatum facilis tempore saepe? Odio mollitia voluptatum repellat ipsam doloremque soluta natus deserunt. Debitis quaerat doloribus ullam dolor quod perferendis eligendi, dignissimos iure dolore illum ex similique recusandae necessitatibus, eaque accusantium. 
        <p>Eaque expedita repellendus commodi? Ut necessitatibus temporibus modi exercitationem consequuntur esse ipsa at aliquam laboriosam, illo corrupti? Mollitia optio doloremque possimus excepturi, aperiam placeat doloribus consectetur, in eos consequatur vel, ea dolorum soluta. Ipsam repudiandae temporibus reprehenderit labore, doloribus provident voluptate facere laboriosam consequatur consequuntur reiciendis quam illo consectetur commodi iure distinctio sed dolorem aspernatur animi explicabo architecto aut vel? Placeat, rem. Consequuntur assumenda possimus ut qui corporis! Itaque eveniet nisi quis, mollitia doloremque laudantium totam! Dolores impedit incidunt aperiam autem rem eum a at iusto suscipit laborum fugiat fugit architecto vero sint id, facilis ex delectus! At sequi quia perferendis, corrupti ad ipsum in consequatur obcaecati. At magnam aspernatur sequi repellendus vero dolor recusandae maxime iure provident suscipit laudantium labore ducimus unde, rerum assumenda animi ad soluta amet architecto. Eum sint tempora natus dolorum suscipit labore placeat maiores odio aliquid aliquam aut, est fugit voluptas! Nemo ipsa aliquid nobis delectus et assumenda ullam magni placeat deserunt mollitia sunt, amet hic error consequatur impedit ex debitis, culpa ratione minus? Assumenda, in. </p> <p> Fuga ea totam facere nostrum accusantium, reprehenderit aperiam sed perspiciatis sunt excepturi hic et quibusdam iure nisi voluptatem placeat enim inventore iste libero consequuntur saepe tenetur laborum quas! Iste ipsam quibusdam atque velit iusto fugiat suscipit, quam eum similique eligendi sunt quos quae. Atque necessitatibus vitae ducimus recusandae. Sunt facere, magni voluptatem cupiditate ad illum eius, aperiam repellendus tempora natus quidem iure nemo. Animi, ratione. Recusandae, quo! Numquam, quaerat. Reprehenderit laborum est dignissimos, sapiente nostrum itaque aut odio molestiae corporis. Harum animi consequatur, inventore consequuntur neque, porro, a totam doloribus quisquam eaque tempora cum maxime?</p><p>Quasi nisi similique laborum ratione corporis dicta. Ipsam, numquam nulla commodi praesentium harum beatae officiis, facere soluta et fuga provident nobis. Nesciunt, deserunt pariatur quis reiciendis vel magnam? Vitae asperiores aliquam illo numquam illum tempora praesentium voluptatibus incidunt explicabo omnis voluptate sit earum veniam expedita ratione qui ipsam laborum repudiandae quaerat ullam dignissimos temporibus, iure inventore. Iusto distinctio obcaecati officia deleniti quibusdam!</p>
</div>
@endforeach
@endsection